---

- name: configure provisioning templates
  theforeman.foreman.provisioning_template:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    name: "{{ provisioning_template.name }}"
    state: "{{ provisioning_template.state | default(omit) }}"
    file_name: "{{ provisioning_template.file }}"
    organizations: "{{ provisioning_template | json_query('organizations[*].name') | list }}"
    locations: "{{ provisioning_template | json_query('locations[*].name') | list }}"
  loop_control:
    loop_var: provisioning_template
  loop: "{{ satellite.foreman.provisioning_templates }}"
  when:
    - satellite.foreman.provisioning_templates is defined
  delegate_to: "{{ delegate_host }}"
