- name: repo sync | get all repositories
  theforeman.foreman.resource_info:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    resource: repositories
  register: repositories

- name: repo sync | Kick off repository sync tasks
  theforeman.foreman.repository_sync:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    product: "{{ item.product.name }}"
    repository: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
  loop: "{{ repositories.resources }}"
  when: item.url  # Not all repositories have a URL

