- name: "config subnets | create or update subnets"
  oasis_roles.satellite.subnet:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
    gateway: "{{ item.gateway }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    boot_mode: "{{ item.boot_mode | default(omit) }}"
    ipam: "{{ item.ipam | default(omit) }}"
    dhcp_proxy: "{{ item.dhcp_proxy | default(omit) }}"
    tftp_proxy: "{{ item.tftp_proxy | default(omit) }}"
    dns_proxy: "{{ item.dns_proxy | default(omit) }}"
    template_proxy: "{{ item.template_proxy | default(omit) }}"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    domains: "{{ item.domains }}"
    organizations: "{{ item.organizations }}"
    locations: "{{ item.locations }}"
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    state: present
  with_items: "{{ satellite_subnets }}"
