---

- name: configure custom products
  theforeman.foreman.product:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    name: "{{ product.1.product }}"
    gpg_key: "{{ product.1.content_credential_name }}"
    sync_plan: daily
  when:
    - product.1.product is defined
    - product.1.content_credential_name is defined
  loop_control:
    loop_var: product
  loop: "{{ organization.content_views | subelements('repos') }}"
  delegate_to: "{{ delegate_host }}"
