---

- name: configure lifecycle environments
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite.admin_username }}"
    password: "{{ satellite.admin_password }}"
    validate_certs: false
    server_url: "{{ satellite_url }}"
    organization: "{{ organization.organization_name }}"
    name: "{{ lifecycle_environment.name }}"
    prior: "{{ lifecycle_environment.prior }}"
    description: "{{ lifecycle_environment.description | default(omit) }}"
  loop_control:
    loop_var: lifecycle_environment
  loop: "{{ organization.lifecycle_environments }}"
  delegate_to: "{{ delegate_host }}"
