# default vars for rhsm role
satellite_rhn_activation_key: "{{ lookup('env', 'SATELLITE_RHN_AK') }}"
satellite_rhn_org: "{{ lookup('env', 'SATELLITE_RHN_ORG')}}"
satellite_rhn_pool_id: "{{ lookup('env', 'SATELLITE_RHN_POOL_ID')}}"
satellite_rhn_connect: "{{ lookup('env', 'SATELLITE_RHN_CONNECT') }}"
satellite_rhn_username: "{{ lookup('env', 'SATELLITE_RHN_USER') }}"
satellite_rhn_password: "{{ lookup('env', 'SATELLITE_RHN_PASSWORD') }}"
satellite_version: "{{ lookup('env', 'SATELLITE_VERSION') }}"
satellite_rhelver: "{{ lookup('env', 'SATELLITE_RHELVER') | mandatory }}"
satellite_content_source: "{{ lookup('env', 'SATELLITE_CONTENT_SOURCE') }}"
